### ISSUE TITLE
Error 404 trying to access http://localhost:8081/api/champion/keys

### ISSUE THREAD

**Issue by rodritwm** [lassesuomela/infiniteloldle#110]
Hello i want to download all resources like the images and icons and im getting that 404 while using the python script.
Thanks!
![Screenshot_5](https://github.com/lassesuomela/infiniteloldle/assets/36836716/6670cb1c-ebf7-4074-921a-3980efb2568a)

**Comment by lassesuomela** [comment]
Hey, try using /dev/api/* instead of /api/* those python scripts have not been updated in a while so they might or might not perform properly
